// Spaceward Ho! web remake — text data from the original resources
// (star, ship, computer and tech-level names, tips).
(function (root) {
const HODATA = {
 "starNames": [
  "Sol",
  "Sirius",
  "Canopus",
  "Vega",
  "Rigel",
  "Capella",
  "Procyon",
  "Mira",
  "Altair",
  "Antares",
  "Spica",
  "Pollux",
  "Castor",
  "Deneb",
  "Regulus",
  "Polaris",
  "Algol",
  "Proxima",
  "Alban",
  "Thuban",
  "Mizar",
  "Alcor",
  "Doobie",
  "Merak",
  "Phad",
  "Megrez",
  "Alioth",
  "Alkaid",
  "Mintaka",
  "Alnitak",
  "Atlas",
  "Remus",
  "Alcyon",
  "Electra",
  "Maia",
  "Merope",
  "Taygeta",
  "Sterope",
  "Hadar",
  "Quark",
  "Mimosa",
  "Adhara",
  "Shaula",
  "Nath",
  "Almak",
  "Alshain",
  "Tarazed",
  "Hamal",
  "Izar",
  "Shedir",
  "Menkar",
  "Diphda",
  "Etamin",
  "Acamar",
  "Alhena",
  "Alphard",
  "Arneb",
  "Nihal",
  "Saiph",
  "Markab",
  "Kansas",
  "Enif",
  "Nunki",
  "Kokab",
  "Ain",
  "Ancha",
  "Arkab",
  "Atik",
  "Atria",
  "Shadow",
  "Azha",
  "Baham",
  "Beid",
  "Botein",
  "Caph",
  "Coxa",
  "Cursa",
  "Dabih",
  "Furud",
  "Gedi",
  "Gienah",
  "Heka",
  "Keid",
  "Maaz",
  "Matar",
  "Mirfak",
  "Murzim",
  "Delta",
  "Ozworld",
  "Okda",
  "Phact",
  "Propus",
  "Rana",
  "Risha",
  "Sabik",
  "Petro",
  "Syrma",
  "Tarf",
  "Wasat",
  "Wazn",
  "Yed",
  "Yildun",
  "Zaniah",
  "Zaurac",
  "Zosma",
  "Ylum",
  "Arrakis",
  "Akworld",
  "Colma",
  "Moria",
  "Foundat",
  "Trantor",
  "Barsoom",
  "Aurora",
  "Fluffy",
  "Lennon",
  "Seti Alpha\r",
  "Paradox",
  "Santa Fe",
  "Victoria",
  "Fez",
  "Binar",
  "Nemesis",
  "Harkon",
  "Talos",
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Pisces",
  "Canis",
  "Ursa",
  "Beta",
  "Zeta",
  "Upsilon",
  "Rho",
  "Cepheus",
  "Calvin",
  "Hobbes",
  "Pooh",
  "Tigger",
  "Bambi",
  "Dumbo",
  "Tweety",
  "Bugs",
  "Torino",
  "Denali",
  "St. Moritz",
  "Sauron",
  "Smaug",
  "Thune",
  "Thorin",
  "Gollum",
  "Fazaron",
  "Trellor",
  "Regor",
  "Basil",
  "Ursula",
  "Styx",
  "Lentor",
  "Sooltar",
  "Romula",
  "Vulcan",
  "Hobbiton",
  "Kessel",
  "Redox",
  "Sith",
  "Yavin",
  "Quatro",
  "Remulak",
  "Kathoon",
  "Thanos",
  "Krypton",
  "Darven",
  "Gotham",
  "Klah",
  "Zaphod",
  "Turin",
  "Krikkit",
  "Vogon",
  "Argot",
  "Willy",
  "Sirgil",
  "Ender",
  "Wobbler",
  "Hoth",
  "Naboo",
  "Fomalhaut",
  "Alpheratz",
  "Arcturus",
  "Regulus",
  "Antares",
  "Aldebaran",
  "Betelgeuse",
  "Nekkar",
  "Seginus",
  "Benetnasch",
  "Murphrid",
  "Alkalurops",
  "Acubens",
  "Tegmen",
  "Denebola",
  "Aldhafera",
  "Zavijava",
  "Alderamin",
  "Kornephoros",
  "Yed Prior",
  "Al Niyat",
  "Andromeda",
  "Sheratan",
  "Achernar",
  "A Centauri",
  "Wolf 359",
  "Genesis",
  "Kirby",
  "B Centauri",
  "Tatooine",
  "Alderran",
  "Klendathu",
  "Betazed",
  "Cardassia",
  "Delios VII",
  "Ferenginar",
  "I'dania",
  "Kostolian",
  "Narenda III",
  "Ocampa",
  "Risa",
  "Talax",
  "Xendi Sabu",
  "Yadera",
  "Corellia",
  "Coruscant",
  "Geonosis",
  "Kashyyyk",
  "Arbra",
  "Kamino",
  "Lyra",
  "Chetco",
  "Cassidy",
  "Zed",
  "Arkanatex",
  "Zoltar VII",
  "Soph",
  "Fluxer",
  "Doldunn",
  "Lochia",
  "Crolax",
  "Kylothia",
  "Cerebrax",
  "Quaz"
 ],
 "maleNames": [
  "Peter",
  "Joe",
  "Timmer",
  "Howard",
  "Bob",
  "Ed",
  "Mark",
  "Guy",
  "Ben",
  "Dan",
  "Kon",
  "Brennan",
  "John",
  "Mike",
  "Dave",
  "Steve",
  "Rosko",
  "Willy",
  "Jack",
  "Albert"
 ],
 "femaleNames": [
  "Christie",
  "Suzy",
  "Ann",
  "Julia",
  "Nancy",
  "Xena",
  "Athena",
  "Heather",
  "Caryl",
  "Jennifer",
  "Kathy",
  "Kate",
  "Jane",
  "Paula",
  "Michelle",
  "Iris",
  "Pam",
  "Liz",
  "Alexis",
  "Grace",
  "Sabrina",
  "Claire"
 ],
 "shipNames": {
  "scout": [
   "Needle",
   "Explorer",
   "Looker",
   "Columbus",
   "Magellan",
   "Intrepid",
   "Wanderer",
   "Rudolph",
   "Eagle",
   "Sparrow",
   "Ranger",
   "Whisper",
   "Weasel",
   "Enterprise",
   "De Gama"
  ],
  "dread": [
   "Big Surprise",
   "HelliMoon",
   "Mass Murder",
   "Watch Out!",
   "Terror",
   "Godzilla",
   "Mammoth",
   "Tyrannosaurus",
   "Galactus",
   "Hercules",
   "Monster X",
   "Nightmare",
   "Brontosaurus",
   "Destructor",
   "Annihilator"
  ],
  "fighter": [
   "Reliant",
   "Demon",
   "Hurricane",
   "Typhoon",
   "Slasher",
   "Patton",
   "Stingray",
   "Blaster",
   "Talon",
   "Serpent",
   "Dragon",
   "Tornado",
   "Wraith",
   "Storm",
   "Dagger"
  ],
  "tanker": [
   "Chevron",
   "Union 76",
   "Shell",
   "Exxon",
   "Texaco",
   "Arco",
   "Mobil",
   "BP",
   "Apollo Oil",
   "Diesel",
   "Rotten Robbie",
   "Full Serve",
   "Valdez",
   "Premium",
   "Unleaded"
  ],
  "colony": [
   "Spreader",
   "Mother",
   "Expander",
   "Nina",
   "Pinta",
   "Santa Maria",
   "Stork",
   "Freedom",
   "People Mover",
   "Discover",
   "Taurus",
   "Minerva",
   "Egg",
   "Peaceful",
   "Hardy"
  ],
  "satellite": [
   "Defender",
   "Stopper",
   "Protector",
   "Eye",
   "Armor",
   "Shield",
   "Peach",
   "Washington",
   "Gabriel",
   "Sun Dog",
   "Mercy",
   "Vision",
   "Pebble",
   "Rock",
   "Stone"
  ],
  "bio": [
   "Medusa",
   "Slither",
   "Snake",
   "Gobbler",
   "Digester",
   "Big Stomach",
   "Breakfast",
   "Lunch",
   "Dinner",
   "Midnight Snack",
   "Rust Monster",
   "Gelatinous Cube",
   "Compost Pile",
   "Disposal",
   "Trash Compactor"
  ],
  "decoy": [
   "Decoy",
   "Phantom",
   "Mirage",
   "Bluff",
   "Ghost"
  ]
 },
 "techNames": {
  "range": [
   "1",
   "2",
   "3",
   "4",
   "5",
   "6",
   "Topping off the Tanks",
   "Fusion Pile",
   "Magneto-Hydrodynamic Power",
   "Allotropic Iron",
   "Gravitic Battery",
   "Quantum Energy Storage",
   "Singularity",
   "Plasma Siphon",
   "Muon Ladder",
   "There and Back",
   "Quark Grinder",
   "Pulsar Radiant",
   "Anti-Matter",
   "Star Harness"
  ],
  "speed": [
   "1",
   "Solar Sail",
   "Ion Rocket",
   "Gravitic Slingshot",
   "Fusion Dump Drive",
   "Relativity Drive",
   "Trans-Light",
   "Hyperspace",
   "Rift Drive",
   "Hawking Propulsion System",
   "Hyper-Rift Drive",
   "PowerPC™",
   "Trans-Rift Hyper Drive",
   "Hawking Trans-Hyper Drive",
   "Time Distortion",
   "Quantum Continuum",
   "Already There",
   "Speedy Gonzalez™",
   "Teleportation",
   "Yesterday Drive"
  ],
  "weapons": [
   "1",
   "2",
   "Mass Driver Cannon",
   "Laser 20",
   "Turbolaser",
   "Maser",
   "Gamma-Ray Laser",
   "Spectrum Cannon",
   "Energy Ball",
   "Nuclear Magnetic Resonance",
   "Phase Disruption",
   "Focused Quark Beam",
   "Hard Pixel",
   "Tachyon Cannon",
   "+5 Rustproof Vorpal",
   "Hyperspace Pulse",
   "Delta Particle Stream",
   "Neutron Compression",
   "Nova Cannon",
   "Galactic Disruption",
   "Advanced Space-Time Annihilation"
  ],
  "shields": [
   "1",
   "2",
   "Armored Hull",
   "Mass Repulser",
   "Energy Dispersion",
   "Deflector",
   "Energy Bonded Armor",
   "Anti-Energy",
   "Quark Shell",
   "Delta Wave",
   "Energy Injestor",
   "Refractor Field",
   "Holographic Decoy",
   "Stasis Flicker",
   "Conversion Field",
   "Tao Wave",
   "Gluon Armor",
   "Hide behind a big rock",
   "+5 Blessed Plate Mail",
   "Displacer Field"
  ],
  "mini": [
   "Integrated Circuit",
   "Integrated Chip",
   "Large Scale Integration",
   "VLSI",
   "Wonkavision",
   "Ultra-microscopic",
   "Nanoscopic",
   "Advanced Nanoscopic",
   "Really Amazingly Small",
   "Yellow Polka Dot Bikini",
   "Sub-Atomic",
   "Partial Lepton",
   "Quark",
   "Sub-Quark",
   "Micro-Quark",
   "Nano-Quark",
   "Advanced Nano-Quark",
   "Bikini Again (Thought it was funny)",
   "Quantum Superstring",
   "Sub-Quantum Superstring"
  ]
 },
 "tips": [
  "Click here to make this message go away. Click on the clock to end your turn.",
  "Fleets appear as dots next to your planets. Click one and drag it to send it to another star.",
  "Play with the spending bars. Conquer the galaxy. Gain ranks to unlock more game options. Enjoy.",
  "Ships with higher Speed Tech shoot first.",
  "Dots by your planet mean you have ships orbiting around it. Fleets are on the right; satellites are on the left.",
  "Good planets look “prettier” than bad planets when you explore them.",
  "Range is how far your ships can reach.",
  "Satellites can't move, but they shoot just as well as any other ship.",
  "There's a limited amount of metal in the game.",
  "Miniaturization makes ships cost more money, but less metal.",
  "Radical Tech can have a variety of effects.",
  "Be careful with your metal--it can easily run out.",
  "Click and hold for a second to cancel a fleet's movement.",
  "Build Satellites to protect vulnerable planets.",
  "Colonize good planets with Colony ships.",
  "Scout ships have higher Range, but lower Weapons and Shields.",
  "If your Weapons are higher than the opponent's Shields, you'll do lots of damage.",
  "If your Shields are higher than the opponents Weapons, he'll barely hurt you.",
  "Lots of ships can make up for having low Technology.",
  "You get money every turn.",
  "Good planets are close to 1.0 G.",
  "Good planets are close to 72°F (20°C).",
  "Each player has a different idea of what a good planet is.",
  "If a planet is over 2.5 G or below 0.4 G, it will never make a profit.",
  "Abandon bad planets after you strip-mine them.",
  "Terraforming improves a planet's temperature.",
  "Mining takes metal from a planet and puts it into your reserve.",
  "Savings puts money away for shipbuilding.",
  "Savings generates extra income.",
  "If you go into debt, part of your income goes to pay interest.",
  "If you have a fleet with fighters and a colony ship, mark the colony ship to arrive late. It'll probably survive longer.",
  "Ships in a fleet that arrive late may miss the worst initial battle.\r",
  "Offensive ships attack better but defend worse.",
  "Defensive ships defend better but attack worse.",
  "There's a contextual menu in the map window for convenience.",
  "Hold down the option key and click planets to specify your fleet's path more exactly.",
  "Put multiple ships in the same fleet with Organize Fleets. ",
  "Option-drag in Organize Fleets to split up ship piles.",
  "Use the graph to see how well you're doing technology-wise vs. the other players.",
  "The first person in the player list is winning.",
  "If you've just started, you might want to try turning on auto-play and watching.",
  "If you and your allies arrive at  a star in the same turn, they'll fight side-by-side in battle.",
  "Armageddons make the galaxy smaller."
 ]
};
if (typeof module !== 'undefined') module.exports = HODATA; else root.HODATA = HODATA;
})(this);
