// Spaceward Ho! web remake — text data from the original resources
// (star, ship, computer and tech-level names, tips, report-message templates
// from STR# 6020, help hints from STR# 6021 and alerts from STR# 6004).
// Report n (1-based) is the original's message number 999 + n.
(function (root) {
const HODATA = {
 "starNames": [
  "Sol",
  "Sirius",
  "Canopus",
  "Vega",
  "Rigel",
  "Capella",
  "Procyon",
  "Mira",
  "Altair",
  "Antares",
  "Spica",
  "Pollux",
  "Castor",
  "Deneb",
  "Regulus",
  "Polaris",
  "Algol",
  "Proxima",
  "Alban",
  "Thuban",
  "Mizar",
  "Alcor",
  "Doobie",
  "Merak",
  "Phad",
  "Megrez",
  "Alioth",
  "Alkaid",
  "Mintaka",
  "Alnitak",
  "Atlas",
  "Remus",
  "Alcyon",
  "Electra",
  "Maia",
  "Merope",
  "Taygeta",
  "Sterope",
  "Hadar",
  "Quark",
  "Mimosa",
  "Adhara",
  "Shaula",
  "Nath",
  "Almak",
  "Alshain",
  "Tarazed",
  "Hamal",
  "Izar",
  "Shedir",
  "Menkar",
  "Diphda",
  "Etamin",
  "Acamar",
  "Alhena",
  "Alphard",
  "Arneb",
  "Nihal",
  "Saiph",
  "Markab",
  "Kansas",
  "Enif",
  "Nunki",
  "Kokab",
  "Ain",
  "Ancha",
  "Arkab",
  "Atik",
  "Atria",
  "Shadow",
  "Azha",
  "Baham",
  "Beid",
  "Botein",
  "Caph",
  "Coxa",
  "Cursa",
  "Dabih",
  "Furud",
  "Gedi",
  "Gienah",
  "Heka",
  "Keid",
  "Maaz",
  "Matar",
  "Mirfak",
  "Murzim",
  "Delta",
  "Ozworld",
  "Okda",
  "Phact",
  "Propus",
  "Rana",
  "Risha",
  "Sabik",
  "Petro",
  "Syrma",
  "Tarf",
  "Wasat",
  "Wazn",
  "Yed",
  "Yildun",
  "Zaniah",
  "Zaurac",
  "Zosma",
  "Ylum",
  "Arrakis",
  "Akworld",
  "Colma",
  "Moria",
  "Foundat",
  "Trantor",
  "Barsoom",
  "Aurora",
  "Fluffy",
  "Lennon",
  "Seti Alpha\r",
  "Paradox",
  "Santa Fe",
  "Victoria",
  "Fez",
  "Binar",
  "Nemesis",
  "Harkon",
  "Talos",
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Pisces",
  "Canis",
  "Ursa",
  "Beta",
  "Zeta",
  "Upsilon",
  "Rho",
  "Cepheus",
  "Calvin",
  "Hobbes",
  "Pooh",
  "Tigger",
  "Bambi",
  "Dumbo",
  "Tweety",
  "Bugs",
  "Torino",
  "Denali",
  "St. Moritz",
  "Sauron",
  "Smaug",
  "Thune",
  "Thorin",
  "Gollum",
  "Fazaron",
  "Trellor",
  "Regor",
  "Basil",
  "Ursula",
  "Styx",
  "Lentor",
  "Sooltar",
  "Romula",
  "Vulcan",
  "Hobbiton",
  "Kessel",
  "Redox",
  "Sith",
  "Yavin",
  "Quatro",
  "Remulak",
  "Kathoon",
  "Thanos",
  "Krypton",
  "Darven",
  "Gotham",
  "Klah",
  "Zaphod",
  "Turin",
  "Krikkit",
  "Vogon",
  "Argot",
  "Willy",
  "Sirgil",
  "Ender",
  "Wobbler",
  "Hoth",
  "Naboo",
  "Fomalhaut",
  "Alpheratz",
  "Arcturus",
  "Regulus",
  "Antares",
  "Aldebaran",
  "Betelgeuse",
  "Nekkar",
  "Seginus",
  "Benetnasch",
  "Murphrid",
  "Alkalurops",
  "Acubens",
  "Tegmen",
  "Denebola",
  "Aldhafera",
  "Zavijava",
  "Alderamin",
  "Kornephoros",
  "Yed Prior",
  "Al Niyat",
  "Andromeda",
  "Sheratan",
  "Achernar",
  "A Centauri",
  "Wolf 359",
  "Genesis",
  "Kirby",
  "B Centauri",
  "Tatooine",
  "Alderran",
  "Klendathu",
  "Betazed",
  "Cardassia",
  "Delios VII",
  "Ferenginar",
  "I'dania",
  "Kostolian",
  "Narenda III",
  "Ocampa",
  "Risa",
  "Talax",
  "Xendi Sabu",
  "Yadera",
  "Corellia",
  "Coruscant",
  "Geonosis",
  "Kashyyyk",
  "Arbra",
  "Kamino",
  "Lyra",
  "Chetco",
  "Cassidy",
  "Zed",
  "Arkanatex",
  "Zoltar VII",
  "Soph",
  "Fluxer",
  "Doldunn",
  "Lochia",
  "Crolax",
  "Kylothia",
  "Cerebrax",
  "Quaz"
 ],
 "maleNames": [
  "Peter",
  "Joe",
  "Timmer",
  "Howard",
  "Bob",
  "Ed",
  "Mark",
  "Guy",
  "Ben",
  "Dan",
  "Kon",
  "Brennan",
  "John",
  "Mike",
  "Dave",
  "Steve",
  "Rosko",
  "Willy",
  "Jack",
  "Albert"
 ],
 "femaleNames": [
  "Christie",
  "Suzy",
  "Ann",
  "Julia",
  "Nancy",
  "Xena",
  "Athena",
  "Heather",
  "Caryl",
  "Jennifer",
  "Kathy",
  "Kate",
  "Jane",
  "Paula",
  "Michelle",
  "Iris",
  "Pam",
  "Liz",
  "Alexis",
  "Grace",
  "Sabrina",
  "Claire"
 ],
 "shipNames": {
  "scout": [
   "Needle",
   "Explorer",
   "Looker",
   "Columbus",
   "Magellan",
   "Intrepid",
   "Wanderer",
   "Rudolph",
   "Eagle",
   "Sparrow",
   "Ranger",
   "Whisper",
   "Weasel",
   "Enterprise",
   "De Gama"
  ],
  "dread": [
   "Big Surprise",
   "HelliMoon",
   "Mass Murder",
   "Watch Out!",
   "Terror",
   "Godzilla",
   "Mammoth",
   "Tyrannosaurus",
   "Galactus",
   "Hercules",
   "Monster X",
   "Nightmare",
   "Brontosaurus",
   "Destructor",
   "Annihilator"
  ],
  "fighter": [
   "Reliant",
   "Demon",
   "Hurricane",
   "Typhoon",
   "Slasher",
   "Patton",
   "Stingray",
   "Blaster",
   "Talon",
   "Serpent",
   "Dragon",
   "Tornado",
   "Wraith",
   "Storm",
   "Dagger"
  ],
  "tanker": [
   "Chevron",
   "Union 76",
   "Shell",
   "Exxon",
   "Texaco",
   "Arco",
   "Mobil",
   "BP",
   "Apollo Oil",
   "Diesel",
   "Rotten Robbie",
   "Full Serve",
   "Valdez",
   "Premium",
   "Unleaded"
  ],
  "colony": [
   "Spreader",
   "Mother",
   "Expander",
   "Nina",
   "Pinta",
   "Santa Maria",
   "Stork",
   "Freedom",
   "People Mover",
   "Discover",
   "Taurus",
   "Minerva",
   "Egg",
   "Peaceful",
   "Hardy"
  ],
  "satellite": [
   "Defender",
   "Stopper",
   "Protector",
   "Eye",
   "Armor",
   "Shield",
   "Peach",
   "Washington",
   "Gabriel",
   "Sun Dog",
   "Mercy",
   "Vision",
   "Pebble",
   "Rock",
   "Stone"
  ],
  "bio": [
   "Medusa",
   "Slither",
   "Snake",
   "Gobbler",
   "Digester",
   "Big Stomach",
   "Breakfast",
   "Lunch",
   "Dinner",
   "Midnight Snack",
   "Rust Monster",
   "Gelatinous Cube",
   "Compost Pile",
   "Disposal",
   "Trash Compactor"
  ],
  "decoy": [
   "Decoy",
   "Phantom",
   "Mirage",
   "Bluff",
   "Ghost"
  ]
 },
 "techNames": {
  "range": [
   "1",
   "2",
   "3",
   "4",
   "5",
   "6",
   "Topping off the Tanks",
   "Fusion Pile",
   "Magneto-Hydrodynamic Power",
   "Allotropic Iron",
   "Gravitic Battery",
   "Quantum Energy Storage",
   "Singularity",
   "Plasma Siphon",
   "Muon Ladder",
   "There and Back",
   "Quark Grinder",
   "Pulsar Radiant",
   "Anti-Matter",
   "Star Harness"
  ],
  "speed": [
   "1",
   "Solar Sail",
   "Ion Rocket",
   "Gravitic Slingshot",
   "Fusion Dump Drive",
   "Relativity Drive",
   "Trans-Light",
   "Hyperspace",
   "Rift Drive",
   "Hawking Propulsion System",
   "Hyper-Rift Drive",
   "PowerPC™",
   "Trans-Rift Hyper Drive",
   "Hawking Trans-Hyper Drive",
   "Time Distortion",
   "Quantum Continuum",
   "Already There",
   "Speedy Gonzalez™",
   "Teleportation",
   "Yesterday Drive"
  ],
  "weapons": [
   "1",
   "2",
   "Mass Driver Cannon",
   "Laser 20",
   "Turbolaser",
   "Maser",
   "Gamma-Ray Laser",
   "Spectrum Cannon",
   "Energy Ball",
   "Nuclear Magnetic Resonance",
   "Phase Disruption",
   "Focused Quark Beam",
   "Hard Pixel",
   "Tachyon Cannon",
   "+5 Rustproof Vorpal",
   "Hyperspace Pulse",
   "Delta Particle Stream",
   "Neutron Compression",
   "Nova Cannon",
   "Galactic Disruption",
   "Advanced Space-Time Annihilation"
  ],
  "shields": [
   "1",
   "2",
   "Armored Hull",
   "Mass Repulser",
   "Energy Dispersion",
   "Deflector",
   "Energy Bonded Armor",
   "Anti-Energy",
   "Quark Shell",
   "Delta Wave",
   "Energy Injestor",
   "Refractor Field",
   "Holographic Decoy",
   "Stasis Flicker",
   "Conversion Field",
   "Tao Wave",
   "Gluon Armor",
   "Hide behind a big rock",
   "+5 Blessed Plate Mail",
   "Displacer Field"
  ],
  "mini": [
   "Integrated Circuit",
   "Integrated Chip",
   "Large Scale Integration",
   "VLSI",
   "Wonkavision",
   "Ultra-microscopic",
   "Nanoscopic",
   "Advanced Nanoscopic",
   "Really Amazingly Small",
   "Yellow Polka Dot Bikini",
   "Sub-Atomic",
   "Partial Lepton",
   "Quark",
   "Sub-Quark",
   "Micro-Quark",
   "Nano-Quark",
   "Advanced Nano-Quark",
   "Bikini Again (Thought it was funny)",
   "Quantum Superstring",
   "Sub-Quantum Superstring"
  ]
 },
 "tips": [
  "Click here to make this message go away. Click on the clock to end your turn.",
  "Fleets appear as dots next to your planets. Click one and drag it to send it to another star.",
  "Play with the spending bars. Conquer the galaxy. Gain ranks to unlock more game options. Enjoy.",
  "Ships with higher Speed Tech shoot first.",
  "Dots by your planet mean you have ships orbiting around it. Fleets are on the right; satellites are on the left.",
  "Good planets look “prettier” than bad planets when you explore them.",
  "Range is how far your ships can reach.",
  "Satellites can't move, but they shoot just as well as any other ship.",
  "There's a limited amount of metal in the game.",
  "Miniaturization makes ships cost more money, but less metal.",
  "Radical Tech can have a variety of effects.",
  "Be careful with your metal--it can easily run out.",
  "Click and hold for a second to cancel a fleet's movement.",
  "Build Satellites to protect vulnerable planets.",
  "Colonize good planets with Colony ships.",
  "Scout ships have higher Range, but lower Weapons and Shields.",
  "If your Weapons are higher than the opponent's Shields, you'll do lots of damage.",
  "If your Shields are higher than the opponents Weapons, he'll barely hurt you.",
  "Lots of ships can make up for having low Technology.",
  "You get money every turn.",
  "Good planets are close to 1.0 G.",
  "Good planets are close to 72°F (20°C).",
  "Each player has a different idea of what a good planet is.",
  "If a planet is over 2.5 G or below 0.4 G, it will never make a profit.",
  "Abandon bad planets after you strip-mine them.",
  "Terraforming improves a planet's temperature.",
  "Mining takes metal from a planet and puts it into your reserve.",
  "Savings puts money away for shipbuilding.",
  "Savings generates extra income.",
  "If you go into debt, part of your income goes to pay interest.",
  "If you have a fleet with fighters and a colony ship, mark the colony ship to arrive late. It'll probably survive longer.",
  "Ships in a fleet that arrive late may miss the worst initial battle.\r",
  "Offensive ships attack better but defend worse.",
  "Defensive ships defend better but attack worse.",
  "There's a contextual menu in the map window for convenience.",
  "Hold down the option key and click planets to specify your fleet's path more exactly.",
  "Put multiple ships in the same fleet with Organize Fleets. ",
  "Option-drag in Organize Fleets to split up ship piles.",
  "Use the graph to see how well you're doing technology-wise vs. the other players.",
  "The first person in the player list is winning.",
  "If you've just started, you might want to try turning on auto-play and watching.",
  "If you and your allies arrive at  a star in the same turn, they'll fight side-by-side in battle.",
  "Armageddons make the galaxy smaller."
 ],
 "reports": [
  "Spaceward Ho! by Peter Commons.",
  "Spaceward Ho! DEMO by Peter Commons.",
  "Artwork by Howard Vives and Bob Van de walle.",
  "Your Range Technology has reached level %d.",
  "Your Speed Technology has reached level %d.",
  "Your Weapons Technology has reached level %d.",
  "Your Shield Technology has reached level %d.",
  "Your Miniaturization Technology has reached level %d.",
  "Your Radical researchers have just made another wild discovery!",
  "You have evacuated %s.",
  "%s has gone nova.",
  "%s destroyed your colony at %s. You %slost %d of your ships. %s lost %d. You lost %s people.",
  "Year %d:",
  "Your colony at %s is not receiving sufficient funds to support itself.",
  "You are not supporting %s enough. The people have revolted and now belong to %s",
  "Warning: you are terraforming %s, a planet that will never become profitable.",
  "You have completely terraformed %s.",
  "A volcanic eruption at %s has drastically warmed the temperature to %s!",
  "Your fleet of %s at %s has been dismantled for %s metal.",
  "Your fleet of %s was dismantled while in hyperspace.",
  "Your “%s” ship type has been dismantled. %d of this type scrapped for %s metal.",
  "Your fleet of %s disappeared through a wormhole in space and is lost.",
  "Your %s is waiting to refuel before it can continue on to %s.",
  "Your fleet of %s has arrived at %s.",
  "Your fleet of %s has stopped at %s on the way to %s.",
  "%s’s fleet of %s has arrived at %s.",
  "Your fleet of %s has eaten %s people while refueling at %s.",
  "%s’s fleet of biologicals has eaten %s people while refueling at %s.",
  "%s has run out of metal.",
  "%s has run out of metal. You should probably evacuate it.",
  "%s has just become a profitable colony.",
  "It’s a baby boom! The population at %s has started growing quickly.",
  "%s’s population growth rate has slowed.",
  "You have explored %s. Gravity: %d.%2.2dG. Temp: %s. Metal: %s.",
  "%s has explored %s. Gravity: %d.%2.2dG. Temp: %s. Metal: %s.",
  "You have colonized %s.",
  "You %swon a battle at %s. You %slost %d of your ships. %s lost %d.",
  "You %slost a battle at %s. You %slost %d of your ships. %s lost %d.",
  "%s survived an attack from %s. You %slost %d of your ships; %s lost %d. You lost %s people.",
  "%s says, “I want %s.”",
  "%s says, “You take %s.”",
  "%s says, “I like %s.”",
  "%s says, “I hate %s.”",
  "%s says, “I own %s.”",
  "%s says, “I need money.”",
  "%s says, “I need metal.”",
  "%s says, “Let’s attack %s.”",
  "%s says, “Thank You!”",
  "%s says, “Sorry!”",
  "%s says, “#!$@*$&@•™!”",
  "%s says, “I like planets that are %d.%2.2dG and %s.”",
  "%s says, “I saw %s at %s!”",
  "%s says, “Look at %s.”",
  "%s is cheating.",
  "%s says: %s",
  "You told %s that you want %s.",
  "You told %s that you don’t want %s.",
  "You told %s that you like %s.",
  "You told %s that you hate %s.",
  "You told %s that you own %s.",
  "You told %s that you need money.",
  "You told %s that you need metal.",
  "You told %s, “Let’s attack %.*s.”",
  "You told %s, “Thank You!”",
  "You told %s, “Sorry!”",
  "You said “#!$@*$&@•™!” to %s.",
  "You told %s what gravity and temperature you prefer.",
  "You told %s you saw %s at %.*s.",
  "You told %s all about %s.",
  "Wow! You seem to be doing really well! Congratulations!",
  "Your message to %s: %s",
  "You recovered %s metal from the battle at %s.",
  "%s metal has fallen onto %s from your recent battle.",
  "Oh no! %s people were killed when a heavy meteor shower hit %s.",
  "%s has just been eliminated from the game.",
  "You have just been eliminated from the game.",
  "%s has just won the game.",
  "Your ally %s has just won the game.",
  "Congratulations! You won a %d difficulty game and have earned %s master points.",
  "You are not spending any money on technology research.",
  "The meteor shower destroyed your colony at %s.",
  "Oh, no! All the metal on %s has suddenly disappeared.",
  "Uh-oh! %s has started growing and is turning bright red in hue!",
  "%s has just gone supernova. The planet has been obliterated.",
  "The shock wave from the supernova threw %s metal at %s, killing %s people.",
  "Your %s technology just jumped to %d.",
  "Eeek! A nasty computer bug has broken into your game and started wreaking havoc!",
  "%s has offered to ally with you.",
  "%s no longer wants to ally with you.",
  "You have offered to ally with %s.",
  "You no longer want to ally with %s.",
  "You have formed an alliance with %s.",
  "Your alliance with %s is gone.",
  "%s has offered to be your best buddy.",
  "%s no longer wants to be your best buddy. He just wants to be allies.",
  "You have offered to be best buddies with %s.",
  "You no longer want to be best buddies with with %s. You just want to be allies.",
  "You are now best buddies with %s.",
  "Your best buddy relationship with %s is gone. You're only allies now.",
  "The amount of energy emanating from %s suggests a big battle just took place.",
  "%s has just given you $%s.",
  "%s has just given you %s metal.",
  "You just gave %s $%s.",
  "You just gave %s %s metal.",
  "%s has just surrendered.",
  "%s has just surrendered to %s.",
  "You have just surrendered.",
  "You have just surrendered to %s.",
  "Your mining consortium has just been able to extract an additional %s metal from every planet you have.",
  "Weird weather patterns have allowed astronomers to explore certain far away stars.",
  "Your ship technicians have designed a set of new ships with no development cost.",
  "Your scientists have invented a decoy ship. It can't fight, but it's cheap. Amaze your friends and confuse your enemies.",
  "Your mad scientists have created a space monster ship! It's not too powerful, but it doesn't cost any metal!",
  "Your scientists have discovered how to turn your monitor from black and white to color!",
  "Your scientists apologize, but they seem to be having “hardware problems.”",
  "Your scientists realize you already are running in color, shrug, and go back off to work.",
  "Your archaeologists have found ancient scientific documents from a lost civilization. You can now mine more efficiently.",
  "Your sociologists have discovered how to safely increase the maximum population of your planets!",
  "Your climatologists have discovered how to terraform planets more efficiently.",
  "Your military training program has improved. Your generals are now smarter.",
  "You have improved your recycling program. You can now get more metal from scrapped ships.",
  "You have built a new research facility; tech spending is now 10% more effective.",
  "You've raised the prime lending rate and can now earn 50%% higher interest on savings.",
  "You have renegotiated your line of credit and can now borrow at a 50%% better interest rate.",
  "Your spies have stolen some technological secrets from %s!",
  "You have found a wealth of precious metals and have increased your savings by $%s",
  "Your Radical researchers are hard at work on another discovery!",
  "Warning! Savings is being used to support %s.",
  "Warning! After supporting your planets and paying your interest, you have no money to spend!",
  "Your alliance will win the game next turn if it holds!",
  "Uh-oh! Having to borrow more to pay all your interest!",
  "You don’t have enough money! You’re neglecting your planets! Global warming is taking place!",
  "Due to a lack of funds, one of your fleets can’t be maintained. It is being scrapped.",
  "Oh No! It’s armageddon!",
  "Hmm! The armadeddon device was activated, but there wasn't enough mass in the galaxy to get it to work…",
  "The armageddon device has caused half of the stars to supernova!",
  "%s’s armageddon device has just been turned on!",
  "Whew! %s’s armageddon device was just turned off.",
  "You just received %s metal from someone scrapping a fleet or from a battle over %s.",
  "Congratulations, %s! Your population now exceeds %s!",
  "Your %s tech would have just gone up if you hadn’t been playing the demo version!",
  "%s has just taken over for the computer player %s.",
  "You now have %s Range Technology (%d).",
  "You now have %s Speed Technology (%d).",
  "You now have %s Weapons Technology (%d).",
  "You now have %s Shield Technology (%d).",
  "You now have %s Miniaturization Technology (%d).",
  "%s surrenders to you, giving you $%s.",
  "%s surrenders to you, giving you %s metal.",
  "%s surrenders to you, giving you the planet %s.",
  "Oh no! The Valdez has sprung a leak! The ecology on %s is in shambles! The citizens are suing you for negligence for twice your net worth!",
  "You just watched some of your allies fight a battle at %s.",
  "There were not enough tankers to fully refuel your fleet of %s at %s.",
  "Your fleet of %s is fully refueled and is ready to depart %s for %s.",
  "%s people managed to escape the meteor shower at %s by fleeing to the orbiting colony ship(s).",
  "Designed by Joe Williams.",
  "Your %s can no longer reach %s because some of the ships in the fleet don't have enough range.",
  "It's a miracle! Your scientists have figured out to prevent %s from going supernova.",
  "Wow, that's weird! %s is no longer red and appears not to be in danger of going nova."
 ],
 // the picture (PICT 9000 + n; -1 none) and sound shown with each of the
 // report lines above, in the same order (FUN_1009d670, FUN_1009cff0).
 // Sound 0 = silent; "explore" = 6000/6002/6001 by how good the star is;
 // "elim" = 2001 if the player was your best buddy, else 7021; picture "face" = the
 // winner's face, "tech" = 39 + which technology.
 "reportLook": [[31,7001],[33,7001],[32,7001],[5,2000],[6,2000],[7,2000],[8,2000],[9,2000],[10,2000],[38,7001],[15,7001],[25,2001],[-1,7001],[20,3002],[20,7001],[13,7001],[27,7001],[21,7001],[14,7001],[21,7001],[14,7001],[15,7020],[3,7001],[3,7001],[3,7001],[19,7001],[26,7013],[26,7013],[1,7001],[13,7001],[0,2000],[23,7001],[30,7001],[27,"explore"],[19,"explore"],[27,7018],[36,0],["face",0],[36,0],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,5002],[24,5003],[24,5001],[24,7001],[24,7001],[24,7001],[24,7016],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,7001],[24,5002],[24,5003],[24,5001],[24,7001],[24,7001],[24,7001],[24,7016],[24,7001],[1,7001],[1,7001],[21,3003],[35,"elim"],[37,2001],[34,2001],[35,7021],[35,7021],[20,7001],[21,3003],[15,7001],[15,7001],[15,7001],[16,3003],["tech",2000],[10,7020],[19,7001],[19,7020],[19,7001],[19,7020],[19,7017],[19,2001],[19,7001],[19,7020],[19,7001],[19,7020],[19,7017],[19,2001],[16,7001],[0,7015],[1,7015],[0,7015],[1,7015],[22,2000],[22,2000],[22,2001],[22,2001],[45,7001],[46,7001],[3,7001],[3,7001],[3,7001],[10,7001],[10,7001],[10,7001],[1,2000],[44,2000],[27,2000],[17,2000],[14,2000],[10,2000],[47,2000],[47,2000],[33,2000],[48,2000],[10,7001],[2,7001],[20,7020],[35,2000],[2,7020],[20,7020],[20,7020],[12,8000],[12,7001],[15,2001],[12,8000],[12,7014],[14,2000],[30,7019],[34,7020],[33,7001],[33,7001],[33,7001],[33,7001],[33,7001],[33,7001],[22,7015],[22,7015],[22,7015],[3,5001],[25,0],[3,7001],[3,7001],[30,7014],[33,7001],[3,7001],[15,7014],[15,7014]],
 // the 25 ranks: name, master points needed, what it unlocks (table at
 // 0x100e3f10). Rank N's picture is assets/explore/NN.jpg.
 "ranks": [["City Slicker", 0, ""], ["Shopkeeper", 10, "create a grid-shaped galaxy"], ["Farmer", 25, "play against IQ 125 computers"], ["Miner", 50, "start as a 'Backward' system"], ["Greenhorn", 75, "play 20 years per turn"], ["Sourdough", 100, "let computers start on an 'Advanced' system"], ["Muletender", 150, "play against IQ 150 computers"], ["Cowpoke", 200, "start as a 'Barren' system"], ["Ranch Hand", 250, "play against up to 5 computers"], ["Buckaroo", 300, "play 30 years per turn"], ["Horseman", 400, "play against IQ 175 computers"], ["Horse Breaker", 500, "let computers start on an 'Thriving' system"], ["Cowboy", 750, "play against up to 6 computers"], ["Vaquero", 1000, "create a random galaxy"], ["Deputy", 1500, "play 50 years per turn"], ["Lawman", 2000, "play against IQ 200 computers"], ["Sherriff", 3000, "play against up to 7 computers"], ["Marshall", 5000, "start as an 'Outpost' system"], ["Ranger", 10000, "let computers start on an 'Abundant' system"], ["Gunfighter", 20000, "play against up to 8 computers"], ["Outlaw", 50000, "create a hex-shaped galaxy"], ["Desperado", 100000, "play against best-buddy computers"], ["Shootist", 1000000, ""], ["Antares Kid", 10000000, ""], ["Ho! Champion", 100000000, ""]],
 "hints": [
  "Click here to make this message go away. Click on the clock to end your turn.",
  "Fleets appear as dots next to your planets. Click one and drag it to send it to another star.",
  "Play with the spending bars. Conquer the galaxy. Gain ranks to unlock more game options. Enjoy.",
  "Ships with higher Speed Tech shoot first.",
  "Dots by your planet mean you have ships orbiting around it. Fleets are on the right; satellites are on the left.",
  "Good planets look “prettier” than bad planets when you explore them.",
  "Range is how far your ships can reach.",
  "Satellites can't move, but they shoot just as well as any other ship.",
  "There's a limited amount of metal in the game.",
  "Miniaturization makes ships cost more money, but less metal.",
  "Radical Tech can have a variety of effects.",
  "Be careful with your metal--it can easily run out.",
  "Click and hold for a second to cancel a fleet's movement.",
  "Build Satellites to protect vulnerable planets.",
  "Colonize good planets with Colony ships.",
  "Scout ships have higher Range, but lower Weapons and Shields.",
  "If your Weapons are higher than the opponent's Shields, you'll do lots of damage.",
  "If your Shields are higher than the opponents Weapons, he'll barely hurt you.",
  "Lots of ships can make up for having low Technology.",
  "You get money every turn.",
  "Good planets are close to 1.0 G.",
  "Good planets are close to 72°F (20°C).",
  "Each player has a different idea of what a good planet is.",
  "If a planet is over 2.5 G or below 0.4 G, it will never make a profit.",
  "Abandon bad planets after you strip-mine them.",
  "Terraforming improves a planet's temperature.",
  "Mining takes metal from a planet and puts it into your reserve.",
  "Savings puts money away for shipbuilding.",
  "Savings generates extra income.",
  "If you go into debt, part of your income goes to pay interest.",
  "If you have a fleet with fighters and a colony ship, mark the colony ship to arrive late. It'll probably survive longer.",
  "Ships in a fleet that arrive late may miss the worst initial battle.",
  "Offensive ships attack better but defend worse.",
  "Defensive ships defend better but attack worse.",
  "There's a contextual menu in the map window for convenience.",
  "Hold down the option key and click planets to specify your fleet's path more exactly.",
  "Put multiple ships in the same fleet with Organize Fleets. ",
  "Option-drag in Organize Fleets to split up ship piles.",
  "Use the graph to see how well you're doing technology-wise vs. the other players.",
  "The first person in the player list is winning.",
  "If you've just started, you might want to try turning on auto-play and watching.",
  "If you and your allies arrive at  a star in the same turn, they'll fight side-by-side in battle.",
  "Armageddons make the galaxy smaller.",
  "Order the real version of Spaceward Ho! from Delta Tao at www.spacewardho.net!",
  "Order the real version of Spaceward Ho! from Delta Tao at www.spacewardho.net!",
  "Order the real version of Spaceward Ho! from Delta Tao at www.spacewardho.net!",
  "The real version of Spaceward Ho! will let you ally with other players.",
  "Your Technology levels are limited only in the demo version.",
  "Your Technology levels are limited only in the demo version.",
  "Don't spend money on a Technology if you've reached its limits for the Demo version.",
  "The real version of Spaceward Ho! doesn't have Technology limits.",
  "The real version of Spaceward Ho! has configurable galaxies and opponents."
 ],
 "alerts": [
  "Are you sure you want to leave your current network game?",
  "Do you really want to surrender?",
  "You are no longer surrendering to anyone.",
  "Are you sure you want to destroy half the galaxy? Millions of innocent lives will be lost…",
  "Whew! It's good to see that that clearer heads have prevailed!",
  "Sorry, but you may only give 3 gifts per turn.",
  "Sorry, but there is no one else alive to give or send something to.",
  "Do you really want to scrap all existing ships of this type?",
  "Sorry, but the battle record for this battle is no longer available.",
  "Sorry, but there is already a star with that name. How about a different name?",
  "Sorry, but spacewardho.net already has a game with that name running. Please try a different name.",
  "Please name your galaxy.",
  "Unable to connect to game server at spacewardho.net.",
  "You have become disconnected from spacewardho.net. Try to reconnect if you want.",
  "We haven't heard from the server in a while. It may be down or your connection may be severed. You may want to quit and then try to reconnect.",
  "Sorry, but your assembly lines are full. You must scrap a ship type first before you can design any more ship types.",
  "Sorry, you don't have the details about this battle that your ally fought.",
  "Sorry, but you have no additional information about this battle; all you know is that is was pretty big.",
  "You must fill in all fields with the proper data before you can register.",
  "The serial number you entered is not valid. Please check that you entered it in correctly.",
  "The serial number you have entered has already been registered under a different login/screen name. Please enter the same name you did the first time.",
  "Sorry, but the screen name you have requested has already been taken. Please try a different username.",
  "Sorry, but the screen name you have requested is invalid. Please try again.",
  "Sorry, but Spaceward Ho! cannot connect to the registration server. Please make sure you are connected to the Internet.",
  "Sorry, but this serial number has been overused in some way and has been locked out. Please call tech support for assistance.",
  "Sorry, but this version of Spaceward Ho! only permits network play.",
  "Sorry, but the Registration server is returning an error. You may be trying to connect with an old version of Spaceward Ho! that is no longer compatible.",
  "You were idle for 15 minutes and have been disconnected for spacewardho.net.",
  "Sorry, but you have no detailed information about the battle. All you know was that it was big.",
  "Sorry, but that fleet doesn't have enough fuel to reach the selected destination. You can tell this because there are no arrows on either end of the dragged line.",
  "The serial number you entered is invalid. Please check it and try again.",
  "Are you sure you want to de-register this copy of Spaceward Ho!? It will revert to demo mode.",
  "This copy has been de-registered. You must quit Spaceward Ho! for this operation to be complete.",
  "You are playing with a monitor depth less than millions of colors. Please change to millions if possible, as graphic glitches may otherwise result.",
  "Sorry, but you cannot open saved games in demo mode.",
  "Are you sure you want to build that many scout ships?",
  "Are you sure you want to build that many tankers?",
  "Dorothy, I guess that means we're not in Kansas anymore…",
  "This version of the client is not compatible with the current version of the spacewardho.net server. You will need to upgrade first before you can register."
 ]
};
if (typeof module !== 'undefined') module.exports = HODATA; else root.HODATA = HODATA;
})(this);
